#!/usr/bin/env python3
"""Fine-tune with weather augmentation, then re-measure on the same protocol.

The robustness table says the model loses 83% of its AP in heavy rain. This
script is the intervention: the same architecture, the same data, the same
schedule — only the augmentation pipeline changes. Re-running
``4-bench/bench_quality.py`` afterwards gives a before/after pair on an
identical protocol, which is the only kind of comparison worth reporting.

Runs on the host or on Colab (needs torch + ultralytics). The board never
sees this file.

    python 1-model/finetune_weather.py --weights models/yolov8n_visdrone.pt \
        --data VisDrone.yaml --epochs 60

What the augmentation does, and why it is applied this way
---------------------------------------------------------
Ultralytics' built-in augmentations cover geometry, HSV and mosaic, but not
precipitation. We inject the *same* degradation functions the benchmark uses
(``2-augment/degradations.py``) as a training-time callback, so the training
distribution and the evaluation distribution are generated by identical code.
If they diverged, an improvement could be an artefact of two different rain
models rather than of learning.

Only a fraction of each batch is degraded (``--degrade-prob``). Training on
100% rain would trade clean-weather accuracy for wet-weather accuracy, and
the clean case is still the common one.
"""

from __future__ import annotations

import argparse
import os
import random
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "2-augment"))

import degradations as D  # noqa: E402

# Conditions sampled during training. Deliberately *not* the full benchmark
# set: `bright_up`, `fog_medium` and `blur_light` already retain >93% AP, so
# augmenting for them spends capacity on a problem that does not exist.
TRAIN_CONDITIONS = [
    ("rain_light", 0.30),
    ("rain_medium", 0.30),
    ("rain_heavy", 0.20),
    ("blur_medium", 0.20),
]


def sample_condition(rng: random.Random) -> str:
    r = rng.random()
    acc = 0.0
    for name, w in TRAIN_CONDITIONS:
        acc += w
        if r <= acc:
            return name
    return TRAIN_CONDITIONS[-1][0]


def build_callback(prob: float, seed: int):
    """Return an Ultralytics ``on_preprocess_batch``-style callback."""
    rng = random.Random(seed)

    def _augment(trainer):
        batch = getattr(trainer, "batch", None)
        if batch is None or "img" not in batch:
            return
        imgs = batch["img"]
        # imgs: torch uint8/float tensor (B, 3, H, W), RGB, 0..255 or 0..1
        try:
            import torch
        except ImportError:
            return
        if not isinstance(imgs, torch.Tensor):
            return

        was_float = imgs.dtype.is_floating_point
        scale = 255.0 if (was_float and float(imgs.max()) <= 1.0 + 1e-6) else 1.0

        arr = imgs.detach().cpu()
        arr = (arr * scale) if scale != 1.0 else arr
        arr = arr.clamp(0, 255).to(torch.uint8).numpy()      # (B,3,H,W) RGB

        n_done = 0
        for i in range(arr.shape[0]):
            if rng.random() > prob:
                continue
            cond = sample_condition(rng)
            # (3,H,W) RGB -> (H,W,3) BGR for the degradation functions
            bgr = arr[i].transpose(1, 2, 0)[:, :, ::-1]
            out = D.apply_condition(np.ascontiguousarray(bgr), cond,
                                    seed=rng.randrange(1 << 30))
            arr[i] = out[:, :, ::-1].transpose(2, 0, 1)
            n_done += 1

        if n_done:
            t = torch.from_numpy(arr).to(imgs.device)
            t = t.to(imgs.dtype)
            if scale != 1.0:
                t = t / 255.0
            batch["img"] = t

    return _augment


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--weights", default="yolov8n.pt",
                    help="start point; use your clean-trained best.pt to warm-start")
    ap.add_argument("--data", required=True, help="VisDrone.yaml")
    ap.add_argument("--epochs", type=int, default=60)
    ap.add_argument("--imgsz", type=int, default=640)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--degrade-prob", type=float, default=0.35,
                    help="fraction of images degraded per batch")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--name", default="visdrone_weather")
    ap.add_argument("--device", default=None)
    ap.add_argument("--dry-run", action="store_true",
                    help="validate the augmentation callback and exit")
    args = ap.parse_args()

    if args.dry_run:
        # Exercise the degradation path on a synthetic batch so a typo here is
        # found in two seconds rather than forty minutes into a training run.
        rng = random.Random(args.seed)
        img = np.random.default_rng(0).integers(0, 255, (480, 640, 3), dtype=np.uint8)
        for _ in range(8):
            c = sample_condition(rng)
            out = D.apply_condition(img, c, seed=1)
            assert out.shape == img.shape and out.dtype == np.uint8, c
            print(f"  ok {c:14s} mean {out.mean():6.1f}")
        print("[ok] augmentation path is sound")
        return 0

    try:
        from ultralytics import YOLO
    except ImportError:
        print("[fatal] pip install ultralytics", file=sys.stderr)
        return 2

    model = YOLO(args.weights)
    model.add_callback("on_preprocess_batch",
                       build_callback(args.degrade_prob, args.seed))

    print(f"[info] weather augmentation on {args.degrade_prob:.0%} of images")
    print(f"[info] conditions: {[c for c, _ in TRAIN_CONDITIONS]}")

    model.train(
        data=args.data,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        seed=args.seed,
        name=args.name,
        device=args.device,
        cache="disk",
        # Geometry/colour augmentation stays at Ultralytics defaults so the
        # only difference from the clean baseline is the weather callback.
    )

    print("\nNext, to produce the before/after pair on an identical protocol:")
    print(f"  python 1-model/export_onnx.py --weights runs/detect/{args.name}/weights/best.pt \\")
    print("      --imgsz 640 --out models/yolov8n_visdrone_weather_640.onnx")
    print("  python 4-bench/bench_quality.py --model models/yolov8n_visdrone_weather_640.onnx \\")
    print("      --all-conditions --out results/quality_weather.csv --tag weather-aug")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
